"""empty message

Revision ID: 667e648adb8b
Revises: 
Create Date: 2023-04-18 19:28:12.630254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667e648adb8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('g_auth_verify', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('vacation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('destination', sa.String(length=150), nullable=False),
    sa.Column('flight', sa.String(length=200), nullable=True),
    sa.Column('food', sa.String(length=200), nullable=True),
    sa.Column('lodging', sa.String(length=200), nullable=True),
    sa.Column('souvenirs', sa.String(length=200), nullable=True),
    sa.Column('activities', sa.String(length=200), nullable=True),
    sa.Column('total', sa.String(length=200), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacation')
    op.drop_table('user')
    # ### end Alembic commands ###
